from BuyOrSellEnum import BuyOrSell
from collections import deque
import heapq
from Order import Order

class OrderBook:
    _bestAsk: list[float] # min heap
    _bestBid: list[float] # max heap
    _orderMap: dict[int, Order]
    _volumeMap: dict[tuple[float, BuyOrSell], int]
    _queueMap: dict[tuple[float, BuyOrSell], deque[Order]]

    # generated by Claude because I didn't feel like writing all of this
    def __init__(self, bestAsk=None, bestBid=None, orderMap=None, volumeMap=None, queueMap=None):
        # make them the arguments passed in if they're not None else make them lists or dicts(maps)
        # by default they are None if nothing is passed into the constructor
        self._bestAsk = bestAsk if bestAsk is not None else []
        self._bestBid = bestBid if bestBid is not None else []
        self._orderMap = orderMap if orderMap is not None else {}
        self._volumeMap = volumeMap if volumeMap is not None else {}
        self._queueMap = queueMap if queueMap is not None else {}

    def PlaceOrder(self, order: Order) -> str:
        order_output = ""

        # get which book the order is and its opposite
        if order.side == BuyOrSell.BUY:
            other_book = self._bestAsk
            other_side = BuyOrSell.SELL
            same_book = self._bestBid # i don't use this right now, am not sure if i'll remove this later or not
        else:
            other_book = self._bestBid
            other_side = BuyOrSell.BUY
            same_book = self._bestAsk # i don't use this right now, am not sure if i'll remove this later or not

        # add it into the orderMap
        self._orderMap[order.order_id] = order

        # loop through and fill
        # if we still have volume left and if other_book (bestAsk) is not empty and if bestAsk price is less than what the user wants
        while order.volume > 0 and other_book:
            # get best price on other side
            if order.side == BuyOrSell.BUY:
                best_price = other_book[0] # other_book is the ask (they're selling)
                # break the loop if the price that they're selling from is more than we want to buy for
                if best_price > order.price:
                    break
            else:
                best_price = -(other_book[0]) # negated back to positive
                # other_book in this case is bid (they're buying)
                # break the loop if the price that they want to buy for is less than the price we want to sell for
                if best_price < order.price:
                    break


            queue = self._queueMap.get((best_price, other_side)) # queue is the smallest on the other side
            if not queue: # if we get nothing
                heapq.heappop(other_book) # we pop the smallest from the other book
                continue # continue on

            other_order: Order = queue[0] # top item from the other side
            trade_price, trade_volume = other_order.price, min(order.volume, other_order.volume) # trade price is what the user wants, volume is what we can trade which is either how much the user puts in or how much this price has
            other_order.volume -= trade_volume # decrement the volume in the first order of the other book
            order.volume -= trade_volume # decrement the volume in the order
            self._volumeMap[(best_price, other_side)] -= trade_volume

            # print the transaction if any takes place
            order_output = f"Trade #{other_order.order_id} made by {other_order.client}, taken by {order.client}, {trade_volume} shares at {round(trade_price, 3)}"
            # we use other_order.price bc
            # if we offer to buy a stock for 52 dollars but there's a share up for sell for 50 dollars we buy at 50 and report 50 as the trade price
            # if we offer to sell a stock for 50 dollars but someone wants to buy for 52 we sell it at 52 and report 52 as the trade price

            if other_order.volume == 0: # we've used up all the volume the book had
                self.CancelOrder(other_order.order_id)

        if order.volume > 0: # if we still have volume left after
            self.addOrderToBook(order)

        return order_output


    def addOrderToBook(self, order:Order):
        if (order.price, order.side) not in self._queueMap:
            price_queue: deque[Order] = deque()
            price_queue.append(order)
            self._queueMap[(order.price, order.side)] = price_queue # this price isn't in the queuemap so we go the index and we add a new priority queue based on timestamp and the order
            self._volumeMap[(order.price, order.side)] = order.volume # we then go to the same timestamp on volumemap and add the volume

            # add to _bestAsk or _bestBid
            if order.side == BuyOrSell.SELL: # same_book is _bestAsk which is a minheap
                heapq.heappush(self._bestAsk, order.price)
            else: # same_book is _bestBid which is maxheap: to get this we just negate the price
                heapq.heappush(self._bestBid, (-order.price))
        else:
            self._queueMap[(order.price, order.side)].append(order) # this does exist in volume and queue map so we push a new element into the queue
            self._volumeMap[(order.price, order.side)] += order.volume # we add the volume in here too


    def CancelOrder(self, orderID: int):
        # check if orderID is in ordermap
        if orderID in self._orderMap:
            order = self._orderMap[orderID]
            price_queue = self._queueMap[(order.price, order.side)]

            # remove order from pricequeue
            price_queue.remove(order)

            # decrement from the volume map
            self._volumeMap[(order.price, order.side)] -= order.volume

            if len(price_queue) == 0: # check if price_queue for this price is empty
                self._queueMap.pop((order.price, order.side)) # since this price queue doesn't exist, we can remove it from the queue map
                self._volumeMap.pop((order.price, order.side)) # if price_queue is empty then we remove from volume

            self._orderMap.pop(order.order_id) # remove from ordermap


    def VolumeAtPrice(self, price: float, BuyingOrSelling: BuyOrSell):
        return self._volumeMap[(price, BuyingOrSelling)]
